import mongoose from "mongoose";
import * as dotenv from "dotenv";
import { Seat } from "./models/Seat";
import { ENV } from "./config/env";

dotenv.config();

const seatsData = [
    // Dhaka Division
    { division: "Dhaka Division", seatName: "Dhaka-1", mpName: "Khandaker Abu Ashfaq", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-2", mpName: "Amanullah Aman", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-3", mpName: "Gayeshwar Chandra Roy", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-4", mpName: "Syed Zainul Abedin", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Dhaka-5", mpName: "Mohammad Kamal Hossain", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Dhaka-6", mpName: "Ishraque Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-7", mpName: "Hamidur Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-8", mpName: "Mirza Abbas", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-9", mpName: "Habibur Rashid Habib", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-10", mpName: "Sheikh Rabiul Alam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-11", mpName: "Nahid Islam", party: "National Citizen Party" },
    { division: "Dhaka Division", seatName: "Dhaka-12", mpName: "Saiful Alam Khan Milon", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Dhaka-13", mpName: "Bobby Hajjaj", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-14", mpName: "Mir Ahmad Bin Quasem", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Dhaka-15", mpName: "Shafiqur Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Dhaka-16", mpName: "Md. Abdul Baten", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Dhaka-17", mpName: "Tarique Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-18", mpName: "SM Jahangir Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-19", mpName: "Dewan Md. Salauddin", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Dhaka-20", mpName: "Md Tamiz Uddin", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gazipur-1", mpName: "Md. Mazibur Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gazipur-2", mpName: "M Manjurul Karim Roni", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gazipur-3", mpName: "S. M. Rafiqul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gazipur-4", mpName: "Salahuddin Aiyubi", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Gazipur-5", mpName: "AKM Fazlul Haque Milon", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Kishoreganj-1", mpName: "Mazharul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Kishoreganj-2", mpName: "Jalal Uddin Jalal", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Kishoreganj-3", mpName: "Osman Faruk", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Kishoreganj-4", mpName: "Md Fazlur Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Kishoreganj-5", mpName: "Sheikh Mujibur Rahman Iqbal", party: "Independent politician" },
    { division: "Dhaka Division", seatName: "Kishoreganj-6", mpName: "Md. Shariful Alam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Manikganj-1", mpName: "S A Jinnah Kabir", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Manikganj-2", mpName: "Moinul Islam Khan", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Manikganj-3", mpName: "Afroza Khanam Rita", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Munshiganj-1", mpName: "Sheikh Md. Abdullah", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Munshiganj-2", mpName: "Abdus Salam Azad", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Munshiganj-3", mpName: "Md. Quamruzzaman Ratan", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narayanganj-1", mpName: "Mustafizur Rahman Bhuiyan Dipu", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narayanganj-2", mpName: "Nazrul Islam Azad", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narayanganj-3", mpName: "Azharul Islam Mannan", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narayanganj-4", mpName: "Abdullah Al Amin", party: "National Citizen Party" },
    { division: "Dhaka Division", seatName: "Narayanganj-5", mpName: "Abul Kalam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narsingdi-1", mpName: "Khairul Kabir Khokon", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narsingdi-2", mpName: "Abdul Moyeen Khan", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narsingdi-3", mpName: "Manzur Elahi", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narsingdi-4", mpName: "Sardar Shakhawat Hossain Bokul", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Narsingdi-5", mpName: "Md. Ashraf Uddin", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-1", mpName: "Fakir Mahbub Anam Swapan", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-2", mpName: "Abdus Salam Pintu", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-3", mpName: "Lutfor Rahman Khan Azad", party: "Independent politician" },
    { division: "Dhaka Division", seatName: "Tangail-4", mpName: "Lutfor Rahman Khan Matin", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-5", mpName: "Sultan Salauddin Tuku", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-6", mpName: "Md. Rabiul Awal", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-7", mpName: "Abul Kalam Azad Siddiqui", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Tangail-8", mpName: "Ahmed Azam Khan", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Faridpur-1", mpName: "Md. Elias Molla", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Dhaka Division", seatName: "Faridpur-2", mpName: "Shama Obaed", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Faridpur-3", mpName: "Nayab Yusuf Ahmed", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Faridpur-4", mpName: "Md. Shahidul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gopalganj-1", mpName: "Md. Selimuzzaman Mollah", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gopalganj-2", mpName: "K M Babar", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Gopalganj-3", mpName: "S M Jilani", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Madaripur-1", mpName: "Syed Uddin Ahmad Hanzala", party: "Bangladesh Khelafat Majlis" },
    { division: "Dhaka Division", seatName: "Madaripur-2", mpName: "Jahander Ali Miah", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Madaripur-3", mpName: "Anisur Rahaman", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Rajbari-1", mpName: "Ali Newaz Mahmud Khayyam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Rajbari-2", mpName: "Harunur Rashid", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Shariatpur-1", mpName: "Sayeed Ahmed Aslam", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Shariatpur-2", mpName: "Safiqur Rahman Kiran", party: "Bangladesh Nationalist Party" },
    { division: "Dhaka Division", seatName: "Shariatpur-3", mpName: "Mia Nuruddin Ahmed Apu", party: "Bangladesh Nationalist Party" },

    // Chattogram Division
    { division: "Chattogram Division", seatName: "Chittagong-1", mpName: "Nurul Amin", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-2", mpName: "Vacant", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-3", mpName: "Mostafa Kamal Pasha", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-4", mpName: "Vacant", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-5", mpName: "Mir Mohammad Helal Uddin", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-6", mpName: "Giasuddin Quader Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-7", mpName: "Humam Quader Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-8", mpName: "Ershad Ullah", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-9", mpName: "Mohammad Abu Sufian", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-10", mpName: "Sayeed Al Noman", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-11", mpName: "Amir Khasru Mahmud Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-12", mpName: "Enamul Haque Enam", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-13", mpName: "Sarwar Jamal Nizam", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-14", mpName: "Jashim Uddin Ahammed", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chittagong-15", mpName: "Shajahan Chowdhury", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Chattogram Division", seatName: "Chittagong-16", mpName: "Mohammad Zahirul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Cox's Bazar-1", mpName: "Salahuddin Ahmed", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Cox's Bazar-2", mpName: "Alamgir Mohammad Mahfuzullah Farid", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Cox's Bazar-3", mpName: "Lutfur Rahman Kajal", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Cox's Bazar-4", mpName: "Shahjahan Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Bandarban", mpName: "Saching Prue Jerry", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Rangamati", mpName: "Dipen Dewan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Khagrachhari", mpName: "Wadud Bhuiyan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Brahmanbaria-1", mpName: "M A Hannan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Brahmanbaria-2", mpName: "Rumeen Farhana", party: "Independent politician" },
    { division: "Chattogram Division", seatName: "Brahmanbaria-3", mpName: "Khaled Hossain Mahbub", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Brahmanbaria-4", mpName: "Mushfiqur Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Brahmanbaria-5", mpName: "Md. Abdul Mannan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Brahmanbaria-6", mpName: "Zonayed Saki", party: "Ganosanhati Andolan" },
    { division: "Chattogram Division", seatName: "Chandpur-1", mpName: "A. N. M. Ehsanul Hoque Milan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chandpur-2", mpName: "Md. Jalal Uddin", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chandpur-3", mpName: "Sheikh Farid Ahmed Manik", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Chandpur-4", mpName: "Md. Abdul Hannan", party: "Independent politician" },
    { division: "Chattogram Division", seatName: "Chandpur-5", mpName: "Md. Mominul Haque", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-1", mpName: "Khandaker Mosharraf Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-2", mpName: "Md. Salim Bhuiyan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-3", mpName: "Kazi Shah Mofazzal Hossain Kaikobad", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-4", mpName: "Hasnat Abdullah", party: "National Citizen Party" },
    { division: "Chattogram Division", seatName: "Comilla-5", mpName: "Md. Jashim Uddin", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-6", mpName: "Monirul Haq Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-7", mpName: "Atikul Alam Shawon", party: "Independent politician" },
    { division: "Chattogram Division", seatName: "Comilla-8", mpName: "Zakaria Taher Sumon", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-9", mpName: "Md. Abul Kalam", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-10", mpName: "Md. Mobasher Alam Bhuiyan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Comilla-11", mpName: "Syed Abdullah Muhammad Taher", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Chattogram Division", seatName: "Feni-1", mpName: "Munshi Rafiqul Alam", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Feni-2", mpName: "Joynal Abedin", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Feni-3", mpName: "Abdul Awal Mintoo", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Lakshmipur-1", mpName: "Shahadat Hossain Salim", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Lakshmipur-2", mpName: "Abul Khair Bhuiyan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Lakshmipur-3", mpName: "Shahid Uddin Chowdhury Anee", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Lakshmipur-4", mpName: "A. B. M. Ashraf Uddin", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Noakhali-1", mpName: "Mahbub Uddin Khokon", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Noakhali-2", mpName: "Zainul Abdin Farroque", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Noakhali-3", mpName: "Barkat Ullah Bulu", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Noakhali-4", mpName: "Md. Shahjahan", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Noakhali-5", mpName: "Muhammad Fakrul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Chattogram Division", seatName: "Noakhali-6", mpName: "Abdul Hannan Masud", party: "National Citizen Party" },

    // Rajshahi Division
    { division: "Rajshahi Division", seatName: "Rajshahi-1", mpName: "Mujibur Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Rajshahi-2", mpName: "Mizanur Rahman Minu", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Rajshahi-3", mpName: "Shofiqul Haque Milon", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Rajshahi-4", mpName: "Md. Abdul Bari", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Rajshahi-5", mpName: "Nazrul Islam Mondol", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Rajshahi-6", mpName: "Abu Sayeed Chand", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Natore-1", mpName: "Farzana Sharmin", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Natore-2", mpName: "Ruhul Quddus Talukdar", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Naogaon-1", mpName: "Md. Mostafizur Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Naogaon-2", mpName: "Md. Enamul Haque", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Naogaon-3", mpName: "Fazley Huda Babul", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Naogaon-4", mpName: "Ekramul Bari Tipu", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Naogaon-5", mpName: "Md. Zahidul Islam Dulu", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Naogaon-6", mpName: "Sheikh Md. Rejaul Islam Raju", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Chapai Nawabganj-1", mpName: "Md. Keramat Ali", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Chapai Nawabganj-2", mpName: "Mu. Mizanur Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Chapai Nawabganj-3", mpName: "Md. Nurul Islam Bulbul", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Pabna-1", mpName: "Nazibur Rahman Momen", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Pabna-2", mpName: "AKM Salim Reza Habib", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Pabna-3", mpName: "Mawlana Md. Ali Asghar", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Pabna-4", mpName: "Md. Abu Taleb Mondol", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Pabna-5", mpName: "Shamsur Rahman Simul Biswas", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Sirajganj-1", mpName: "Md. Salim Reza", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Sirajganj-2", mpName: "Iqbal Hassan Mahmood", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Sirajganj-3", mpName: "Md. Aynul Hoque", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Sirajganj-4", mpName: "Rafiqul Islam Khan", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Sirajganj-5", mpName: "Amirul Islam Khan Alim", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Sirajganj-6", mpName: "M. A. Muhit", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-1", mpName: "Kazi Rafiqul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-2", mpName: "Mir Shahe Alam", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-3", mpName: "Md. Abdul Mohit Talukder", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-4", mpName: "Md. Mosharraf Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-5", mpName: "Golam Mohammad Siraj", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-6", mpName: "Rezaul Karim Badsha", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Bogra-7", mpName: "Morshed Milton", party: "Bangladesh Nationalist Party" },
    { division: "Rajshahi Division", seatName: "Joypurhat-1", mpName: "Md. Fazlur Rahman Sayed", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rajshahi Division", seatName: "Joypurhat-2", mpName: "Md. Abdul Bari", party: "Bangladesh Nationalist Party" },

    // Khulna Division
    { division: "Khulna Division", seatName: "Khulna-1", mpName: "Amir Ejaz Khan", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Khulna-2", mpName: "Zahangir Hossain Helal", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Khulna-3", mpName: "Rakibul Islam Bokul", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Khulna-4", mpName: "SK Azizul Bari Helal", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Khulna-5", mpName: "Mohammad Ali Asghar Lobby", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Khulna-6", mpName: "Abul Kalam Azad", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Bagerhat-1", mpName: "Mawlana Md. Moshiur Rahman Khan", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Bagerhat-2", mpName: "Shaikh Monzurul Haque Rahad", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Bagerhat-3", mpName: "Sheikh Faridul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Bagerhat-4", mpName: "Md. Abdul Aleem", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Satkhira-1", mpName: "Md. Izzat Ullah", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Satkhira-2", mpName: "Muhaddis Md. Abdul Khaleque", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Satkhira-3", mpName: "Muhammad Rabiul Bassar", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Satkhira-4", mpName: "Gazi Nazrul Islam", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jessore-1", mpName: "Mawlana Md. Azizur Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jessore-2", mpName: "Md. Moslehuddin Farid", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jessore-3", mpName: "Anindya Islam Amit", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Jessore-4", mpName: "Golam Rasul", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jessore-5", mpName: "Gazi Enamul Haque", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jessore-6", mpName: "Md. Moktar Ali", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Narail-1", mpName: "Biswas Jahangir Alam", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Narail-2", mpName: "Ataur Rahman Bachchu", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Magura-1", mpName: "Munowar Hossain Khan", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Magura-2", mpName: "Nitai Roy Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Jhenaidah-1", mpName: "Md. Asaduzzaman", party: "Bangladesh Nationalist Party" },
    { division: "Khulna Division", seatName: "Jhenaidah-2", mpName: "Ali Azam Md Abu Bakar", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jhenaidah-3", mpName: "Md. Motiar Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Jhenaidah-4", mpName: "Md. Abu Talib", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Chuadanga-1", mpName: "Masud Parves Rasel", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Chuadanga-2", mpName: "Md. Ruhul Amin", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Khulna Division", seatName: "Meherpur-1", mpName: "Mawlana Md. Tajuddin Khan", party: "Bangladesh Jamaat-e-Islami" },

    // Barishal Division
    { division: "Barishal Division", seatName: "Barisal-1", mpName: "Zahir Uddin Swapan", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Barisal-2", mpName: "Sardar Sarfuddin Ahmed", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Barisal-3", mpName: "Zainul Abedin", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Barisal-4", mpName: "Md. Razib Ahsan", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Barisal-5", mpName: "Majibur Rahman Sarwar", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Barisal-6", mpName: "Abul Hossain Khan", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Bhola-1", mpName: "Andaleeve Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Bhola-2", mpName: "Hafiz Ibrahim", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Bhola-3", mpName: "Hafizuddin Ahmed", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Bhola-4", mpName: "Mohammad Nurul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Patuakhali-1", mpName: "Altaf Hossain Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Patuakhali-2", mpName: "Shafiqul Islam Masud", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Barishal Division", seatName: "Patuakhali-3", mpName: "Nurul Haque Nur", party: "Gono Odhikar Parishad" },
    { division: "Barishal Division", seatName: "Patuakhali-4", mpName: "ABM Mosharraf Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Pirojpur-1", mpName: "Masood Sayeedi", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Barishal Division", seatName: "Pirojpur-2", mpName: "Ahammad Sohel Monzoor", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Pirojpur-3", mpName: "Ruhul Amin Dulal", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Barguna-1", mpName: "Mahmudul Hossain Waliullah", party: "Islami Andolan Bangladesh" },
    { division: "Barishal Division", seatName: "Barguna-2", mpName: "Nurul Islam Moni", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Jhalokati-1", mpName: "Rafiqul Islam Jamal", party: "Bangladesh Nationalist Party" },
    { division: "Barishal Division", seatName: "Jhalokati-2", mpName: "Israt Sultana Elen Bhutto", party: "Bangladesh Nationalist Party" },

    // Sylhet Division
    { division: "Sylhet Division", seatName: "Sylhet-1", mpName: "Khandakar Abdul Muktadir", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sylhet-2", mpName: "Tahsina Rushdir Luna", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sylhet-3", mpName: "Mohammad Abdul Malek", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sylhet-4", mpName: "Ariful Haque Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sylhet-5", mpName: "Mufti Abul Hasan", party: "Khelafat Majlish" },
    { division: "Sylhet Division", seatName: "Sylhet-6", mpName: "Emran Ahmed Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Moulvibazar-1", mpName: "Nasir Uddin Ahmed Mithu", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Moulvibazar-2", mpName: "Shawkat Hossain Saku", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Moulvibazar-3", mpName: "M. Naser Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Moulvibazar-4", mpName: "Mujibur Rahman Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Habiganj-1", mpName: "Reza Kibria", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Habiganj-2", mpName: "Abu Mansur Sakhawat Hasan", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Habiganj-3", mpName: "G K Gouse", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Habiganj-4", mpName: "S.M. Faisal", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sunamganj-1", mpName: "Kamruzzaman Kamrul", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sunamganj-2", mpName: "Nasir Uddin Choudhury", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sunamganj-3", mpName: "Mohammad Koysor Ahmed", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sunamganj-4", mpName: "Nurul Islam Nurul", party: "Bangladesh Nationalist Party" },
    { division: "Sylhet Division", seatName: "Sunamganj-5", mpName: "Kalim Uddin Ahmed", party: "Bangladesh Nationalist Party" },

    // Rangpur Division
    { division: "Rangpur Division", seatName: "Rangpur-1", mpName: "Md Rayhan Shirazi", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Rangpur-2", mpName: "A. T. M. Azharul Islam", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Rangpur-3", mpName: "Md. Mahbubur Rahman Belal", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Rangpur-4", mpName: "Akhter Hossen", party: "National Citizen Party" },
    { division: "Rangpur Division", seatName: "Rangpur-5", mpName: "Md Golam Rabbani", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Rangpur-6", mpName: "Md Nurul Amin", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Gaibandha-1", mpName: "Md Mazedur Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Gaibandha-2", mpName: "Md. Abdul Karim", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Gaibandha-3", mpName: "Abul Kawsar Mohammad Nazrul Islam", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Gaibandha-4", mpName: "Shamim Kaisar Lincoln", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Gaibandha-5", mpName: "Md. Abdul Wares", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Kurigram-1", mpName: "Md. Anwarul Islam", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Kurigram-2", mpName: "Atiqur Rahman Mojahid", party: "National Citizen Party" },
    { division: "Rangpur Division", seatName: "Kurigram-3", mpName: "Md Mahbubul Alam", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Kurigram-4", mpName: "Md. Mostafizur Rahman", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Lalmonirhat-1", mpName: "Md. Hasan Rajib Prodhan", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Lalmonirhat-2", mpName: "Md Rokon Uddin Babul", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Lalmonirhat-3", mpName: "Asadul Habib Dulu", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Nilphamari-1", mpName: "Abdus Sattar", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Nilphamari-2", mpName: "Al Faruk Abdul Latif", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Nilphamari-3", mpName: "Obaidullah Salafi", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Nilphamari-4", mpName: "Abdul Muntakim", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Rangpur Division", seatName: "Dinajpur-1", mpName: "Md. Manjurul Islam", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Dinajpur-2", mpName: "Md. Sadiq Riaz", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Dinajpur-3", mpName: "Syed Jahangir Alam", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Dinajpur-4", mpName: "Akhtaruzzaman Mia", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Dinajpur-5", mpName: "AZM Rezwanul Haque", party: "Independent politician" },
    { division: "Rangpur Division", seatName: "Dinajpur-6", mpName: "A. Z. M. Zahid Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Thakurgaon-1", mpName: "Mirza Fakhrul Islam Alamgir", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Thakurgaon-2", mpName: "Abdus Salam", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Thakurgaon-3", mpName: "Jahidur Rahman", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Panchagarh-1", mpName: "Muhammad Nawshad Zamir", party: "Bangladesh Nationalist Party" },
    { division: "Rangpur Division", seatName: "Panchagarh-2", mpName: "Farhad Hossain Azad", party: "Bangladesh Nationalist Party" },

    // Mymensingh Division
    { division: "Mymensingh Division", seatName: "Mymensingh-1", mpName: "Salman Omar Rubel", party: "Independent politician" },
    { division: "Mymensingh Division", seatName: "Mymensingh-2", mpName: "Mufti Muhammadullah", party: "Bangladesh Khelafat Majlis" },
    { division: "Mymensingh Division", seatName: "Mymensingh-3", mpName: "M. Iqbal Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-4", mpName: "Md. Abu Wahab Akand Wahid", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-5", mpName: "Mohammed Zakir Hossain", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-6", mpName: "Md. Quamrul Hassan", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Mymensingh Division", seatName: "Mymensingh-7", mpName: "Mahabubur Rahman Liton", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-8", mpName: "Lutfullahel Majed", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-9", mpName: "Yasser Khan Choudhury", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-10", mpName: "Md. Akhtaruzzaman Bachchu", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Mymensingh-11", mpName: "Fakhruddin Ahmed", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Jamalpur-1", mpName: "M. Rashiduzzaman Millat", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Jamalpur-2", mpName: "Sultan Mahmud Babu", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Jamalpur-3", mpName: "Mostafizur Rahman Babul", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Jamalpur-4", mpName: "Faridul Kabir Talukder Shamim", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Jamalpur-5", mpName: "Shah Md. Wares Ali Mamun", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Netrokona-1", mpName: "Kayser Kamal", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Netrokona-2", mpName: "Md. Anwarul Haque", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Netrokona-3", mpName: "Rafiqul Islam Hilali", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Netrokona-4", mpName: "Lutfozzaman Babar", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Netrokona-5", mpName: "Mashum Mostafa", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Mymensingh Division", seatName: "Sherpur-1", mpName: "Md. Rashedul Islam Rashed", party: "Bangladesh Jamaat-e-Islami" },
    { division: "Mymensingh Division", seatName: "Sherpur-2", mpName: "Mohammad Fahim Chowdhury", party: "Bangladesh Nationalist Party" },
    { division: "Mymensingh Division", seatName: "Sherpur-3", mpName: "Mahmudul Haque Rubel", party: "Bangladesh Nationalist Party" }
];

const seedSeats = async () => {
    try {
        if (!ENV.mongoUri) throw new Error("MONGO_URI not set");
        await mongoose.connect(ENV.mongoUri);
        console.log("Connected to MongoDB...");

        // Remove existing seats before seeding to prevent duplicates
        await Seat.deleteMany({});
        console.log("Cleared existing seats.");

        for (let i = 0; i < seatsData.length; i++) {
            const seat = seatsData[i];
            await Seat.create({
                ...seat,
                lastRecordedAsset: "N/A",
                fiveYearGrowthPercentage: 0,
                order: i + 1,
                partyLogo: seat.party === "Bangladesh Nationalist Party"
                    ? "/BNP.png"
                    : seat.party === "Bangladesh Jamaat-e-Islami"
                        ? "/Jamaat.png"
                        : seat.party === "National Citizen Party"
                            ? "/NCP.png"
                            : undefined
            });
        }

        console.log(`Successfully seeded ${seatsData.length} parliamentary seats!`);
        process.exit(0);
    } catch (error) {
        console.error("Failed to seed seats:", error);
        process.exit(1);
    }
};

seedSeats();
